#!/usr/bin/env python
import os
import sys
from dm_irods import DmIRodsServer
# from dm_irods import DmIRodsServerArguments
sys.path.insert(0,
                os.path.join(
                    os.path.dirname(__file__),
                    "py-socket-server"))
from socket_server import ServerApp


if __name__ == "__main__":
    app = ServerApp(DmIRodsServer,
                    socket_file=DmIRodsServer.get_socket_file())
    app.main()
