#!/usr/bin/env python
"""
Configuration of the dmf-irods-client
Asks for irods conection details and generate configuration and auth file
"""
from dm_irods import dm_iconfig

if __name__ == "__main__":
    dm_iconfig()
